# Generated by Django 5.0.4 on 2024-04-18 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('idDispositivo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreDispositivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEducacional',
            fields=[
                ('idNivelEducacional', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreNivelEducacional', models.CharField(max_length=45)),
                ('promptConfigAsistente', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('idSupervisor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreSupervisor', models.CharField(max_length=45, null=True)),
                ('correo', models.CharField(max_length=200, unique=True)),
                ('clave', models.CharField(max_length=50)),
                ('controlParentalActivado', models.BooleanField()),
                ('gradoBloqueoImagen', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisado',
            fields=[
                ('idSupervisado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreSupervisado', models.CharField(max_length=45)),
                ('clave', models.CharField(max_length=45)),
                ('colorAvatar', models.CharField(max_length=7, null=True)),
                ('imgTopAvatar', models.CharField(max_length=255, null=True)),
                ('colorBottomAvatar', models.CharField(max_length=7, null=True)),
                ('imgCaraAvatar', models.CharField(max_length=255, null=True)),
                ('tipoPeloAvatar', models.IntegerField(null=True)),
                ('colorPeloAvatar', models.CharField(max_length=7, null=True)),
                ('promptConfigAsistente', models.CharField(max_length=4000, null=True)),
                ('idNivelEducacional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.niveleducacional')),
                ('idSupervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('idSesion', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('idDispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dispositivo')),
                ('idSupervisado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supervisado')),
            ],
        ),
        migrations.CreateModel(
            name='SitiosBloqueados',
            fields=[
                ('idSitiosBloqueados', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=4000)),
                ('bloqueoInteligente', models.BooleanField(null=True)),
                ('idSupervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='PalabrasBloqueadas',
            fields=[
                ('idPalabrasBloqueadas', models.IntegerField(primary_key=True, serialize=False)),
                ('palabra', models.CharField(max_length=255)),
                ('bloqueoInteligente', models.BooleanField(null=True)),
                ('idSupervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supervisor')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='idSupervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supervisor'),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('idVisita', models.IntegerField(primary_key=True, serialize=False)),
                ('tituloPagina', models.CharField(max_length=500, null=True)),
                ('url', models.CharField(max_length=4000)),
                ('fechaVisita', models.DateTimeField()),
                ('bloqueado', models.BooleanField()),
                ('enlacesBloqueados', models.IntegerField()),
                ('imagenesBloqueadas', models.IntegerField()),
                ('anunciosBloqueados', models.IntegerField()),
                ('palabrasBloqueadas', models.IntegerField()),
                ('idSesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sesion')),
            ],
        ),
    ]
